name: API Test Automation Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
  # Runs twice daily 
     - cron: 00 18 * * *  # Run Daily 6 PM
     - cron: 00 3 * * *   # Run daily at 8:30 AM
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      checks: write
      actions: read


    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Execute API Tests
      run: mvn clean test -Dsuite=suite -X

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
         name: Logs
         path: logs/
         
    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit
        
         
